# Generated by Django 5.1.6 on 2025-02-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
    ]
